var namespace_nx_xbox =
[
    [ "CInstance", "d8/d5a/class_nx_xbox_1_1_c_instance.html", "d8/d5a/class_nx_xbox_1_1_c_instance" ],
    [ "sBillboardData", "d1/d06/struct_nx_xbox_1_1s_billboard_data.html", "d1/d06/struct_nx_xbox_1_1s_billboard_data" ],
    [ "sBillboardEntry", "de/d25/struct_nx_xbox_1_1s_billboard_entry.html", "de/d25/struct_nx_xbox_1_1s_billboard_entry" ],
    [ "sBillboardManager", "d4/d03/struct_nx_xbox_1_1s_billboard_manager.html", "d4/d03/struct_nx_xbox_1_1s_billboard_manager" ],
    [ "sBillboardMaterialBatch", "db/df4/struct_nx_xbox_1_1s_billboard_material_batch.html", "db/df4/struct_nx_xbox_1_1s_billboard_material_batch" ],
    [ "sCASData", "d4/dec/struct_nx_xbox_1_1s_c_a_s_data.html", "d4/dec/struct_nx_xbox_1_1s_c_a_s_data" ],
    [ "SChar", "d7/d6d/struct_nx_xbox_1_1_s_char.html", "d7/d6d/struct_nx_xbox_1_1_s_char" ],
    [ "SDraw2D", "da/db6/struct_nx_xbox_1_1_s_draw2_d.html", "da/db6/struct_nx_xbox_1_1_s_draw2_d" ],
    [ "sEngineGlobals", "da/db8/struct_nx_xbox_1_1s_engine_globals.html", "da/db8/struct_nx_xbox_1_1s_engine_globals" ],
    [ "SFont", "d0/d7c/struct_nx_xbox_1_1_s_font.html", "d0/d7c/struct_nx_xbox_1_1_s_font" ],
    [ "sFontVert", "d8/db9/struct_nx_xbox_1_1s_font_vert.html", "d8/db9/struct_nx_xbox_1_1s_font_vert" ],
    [ "sLightGlowDetails", "db/d14/struct_nx_xbox_1_1s_light_glow_details.html", "db/d14/struct_nx_xbox_1_1s_light_glow_details" ],
    [ "sMaterial", "da/df5/struct_nx_xbox_1_1s_material.html", "da/df5/struct_nx_xbox_1_1s_material" ],
    [ "sMesh", "d6/d5e/struct_nx_xbox_1_1s_mesh.html", "d6/d5e/struct_nx_xbox_1_1s_mesh" ],
    [ "sMeshEntry", "de/d75/struct_nx_xbox_1_1s_mesh_entry.html", "de/d75/struct_nx_xbox_1_1s_mesh_entry" ],
    [ "sOccluder", "d9/d0c/struct_nx_xbox_1_1s_occluder.html", "d9/d0c/struct_nx_xbox_1_1s_occluder" ],
    [ "sOcclusionPoly", "db/d55/struct_nx_xbox_1_1s_occlusion_poly.html", "db/d55/struct_nx_xbox_1_1s_occlusion_poly" ],
    [ "sParticleSystem", "d0/d3a/struct_nx_xbox_1_1s_particle_system.html", "d0/d3a/struct_nx_xbox_1_1s_particle_system" ],
    [ "sScene", "d8/d68/struct_nx_xbox_1_1s_scene.html", "d8/d68/struct_nx_xbox_1_1s_scene" ],
    [ "sSortedMeshEntry", "dd/d51/struct_nx_xbox_1_1s_sorted_mesh_entry.html", "dd/d51/struct_nx_xbox_1_1s_sorted_mesh_entry" ],
    [ "sSprite", "d4/df2/struct_nx_xbox_1_1s_sprite.html", "d4/df2/struct_nx_xbox_1_1s_sprite" ],
    [ "sSpriteVert", "d8/d4b/struct_nx_xbox_1_1s_sprite_vert.html", "d8/d4b/struct_nx_xbox_1_1s_sprite_vert" ],
    [ "SText", "d1/d80/struct_nx_xbox_1_1_s_text.html", "d1/d80/struct_nx_xbox_1_1_s_text" ],
    [ "sTexture", "d6/dd9/struct_nx_xbox_1_1s_texture.html", "d6/dd9/struct_nx_xbox_1_1s_texture" ],
    [ "sTextureProjectionDetails", "d9/ddf/struct_nx_xbox_1_1s_texture_projection_details.html", "d9/ddf/struct_nx_xbox_1_1s_texture_projection_details" ],
    [ "sTextureWibbleKeyframe", "d5/d06/struct_nx_xbox_1_1s_texture_wibble_keyframe.html", "d5/d06/struct_nx_xbox_1_1s_texture_wibble_keyframe" ],
    [ "sTextureWibbleParams", "d6/da3/struct_nx_xbox_1_1s_texture_wibble_params.html", "d6/da3/struct_nx_xbox_1_1s_texture_wibble_params" ],
    [ "sUVWibbleParams", "d2/d75/struct_nx_xbox_1_1s_u_v_wibble_params.html", "d2/d75/struct_nx_xbox_1_1s_u_v_wibble_params" ],
    [ "sVCWibbleKeyframe", "dd/d57/struct_nx_xbox_1_1s_v_c_wibble_keyframe.html", "dd/d57/struct_nx_xbox_1_1s_v_c_wibble_keyframe" ],
    [ "sVCWibbleParams", "d9/d8f/struct_nx_xbox_1_1s_v_c_wibble_params.html", "d9/d8f/struct_nx_xbox_1_1s_v_c_wibble_params" ],
    [ "sVisibilityTestFIFO", "d2/d46/struct_nx_xbox_1_1s_visibility_test_f_i_f_o.html", "d2/d46/struct_nx_xbox_1_1s_visibility_test_f_i_f_o" ]
];