name: Github_CI

on: [push, pull_request]

jobs:
  build-windows:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:
        Configuration: [Debug, Release]
        Platform: [Win32]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1
    - name: Setup thug.sln from CMake
      shell: cmd
      run: |
        mkdir build && cd build
        cmake .. -G "Visual Studio 16 2019" -A Win32
    - name: MSBuild
      shell: cmd
      working-directory: build
      run: msbuild /p:Configuration=${{ matrix.Configuration }} /p:Platform=${{ matrix.Platform }} thug.sln
